language: rust
sudo: false

os:
 - linux
 - osx

rust:
  # TODO: pick an oldest supported release
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
      - gcc-multilib

env:
  global:
    - RUSTFLAGS=--deny=warnings
    - FEATURES="push process"
    - ARCH=i686

matrix:
  fast_finish: true
  include:
  - env: LINT="dev"
  allow_failures:
  - env: LINT="dev"

script:
  # Test common features.
  - cargo test --features="$FEATURES"
  - |
    if [ $TRAVIS_RUST_VERSION = 'nightly' ]; then
        # Enable dev for clippy linting.
        cargo test --features="$FEATURES $LINT";
        # Lint nightly feature.
        cargo test --features="$FEATURES $LINT nightly";
    fi
  - |
    if [ $TRAVIS_RUST_VERSION = 'stable' ]; then
        # Clean up.
        cargo clean;
        # Test 32-bit versions. rust-prometheus only supports stable rust on 32-bit platforms.
        curl -sSL https://raw.githubusercontent.com/carllerche/travis-rust-matrix/master/test | bash;
    fi
